name: Django CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: ${{ secrets.HEROKU_APP_NAME }} #Must be unique in Heroku
            heroku_email: todesco@gmail.com
   